# Generated by Django 4.1.2 on 2022-10-05 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "usn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("CSE", "CSE"),
                            ("ISE", "ISE"),
                            ("ECE", "ECE"),
                            ("ME", "ME"),
                            ("CIV", "CIV"),
                            ("EEE", "EEE"),
                            ("MAT", "MAT"),
                            ("PHY", "PHY"),
                            ("CHE", "CHE"),
                            ("ENG", "ENG"),
                            ("KAN", "KAN"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                        ],
                        max_length=4,
                    ),
                ),
                ("section", models.CharField(max_length=1)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=students.models.Student)),
                ("fatherName", models.CharField(max_length=50)),
                ("fatherOccupation", models.CharField(max_length=50)),
                ("fatherPhone", models.CharField(max_length=50)),
                ("fatherMail", models.CharField(max_length=50)),
                ("motherName", models.CharField(max_length=50)),
                ("motherOccupation", models.CharField(max_length=50)),
                ("motherPhone", models.CharField(max_length=50)),
                ("motherMail", models.CharField(max_length=50)),
                ("currentAddress", models.CharField(max_length=200)),
                ("permanentAddress", models.CharField(max_length=200)),
                ("hobby", models.EmailField(max_length=50)),
                ("interest", models.EmailField(max_length=50)),
                ("ambition", models.EmailField(max_length=50)),
                (
                    "health",
                    models.EmailField(help_text="Any health issue!", max_length=50),
                ),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                        ],
                        max_length=4,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("concern", models.CharField(max_length=500)),
                ("remark", models.CharField(max_length=500)),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAcademicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                        ],
                        max_length=4,
                    ),
                ),
                ("sub", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=6)),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("remark", models.CharField(max_length=500)),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorGeneralRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                        ],
                        max_length=4,
                    ),
                ),
                ("remark", models.CharField(max_length=500)),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("HOD", "HOD"),
                            ("PRINCIPAL", "PRINCIPAL"),
                            ("AST. PROF", "AST. PROF"),
                            ("PROF", "PROF"),
                            ("L. INSTR", "L. INSTR"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=50)),
                (
                    "user",
                    models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
