# Generated by Django 4.1.2 on 2022-10-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_studentprofile_ambition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="image",
            field=models.ImageField(upload_to="students"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="usn",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
