# Generated by Django 4.1.2 on 2022-12-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_studentprofile_image_alter_studentprofile_usn"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentAcademicPerformance",
        ),
    ]
